import { addDraftPage, attachGeometry, createSession, deletePage, effectiveGeometry, pageById, reorderPage, rotatePage, updatePage, type CaptureGuidance, type CaptureMode, type FilterPreset, type ImageSize, type PageGeometry, type ScanSession, type ScannerState } from "../../../shared/src/scan-session.js";
import type { FilterResult, FrameAnalysisResult, PerceptionFrame, ReconstructionResult, WebPerceptionEngine } from "../perception/contracts.js";

export interface WebScannerState { readonly state: ScannerState; readonly session: ScanSession; readonly activePageId?: string; readonly analysis?: FrameAnalysisResult; readonly guidance: readonly CaptureGuidance[]; readonly error?: string; readonly workerMessages: readonly string[]; }
export class WebScanController {
  private current: WebScannerState;
  constructor(private readonly engine: WebPerceptionEngine, session: ScanSession = createSession(`web-${Date.now()}`)) { this.current = { state: "IDLE", session, guidance: [], workerMessages: [] }; }
  get state(): WebScannerState { return this.current; }
  get engineMode() { return this.engine.mode; }
  private set(patch: Partial<WebScannerState>): void { this.current = { ...this.current, ...patch }; }
  async analyzeFrame(frame: PerceptionFrame): Promise<FrameAnalysisResult> { try { const analysis = await this.engine.analyzeFrame(frame); const state: ScannerState = analysis.captureReadiness === "CAPTURE_NOW" || analysis.captureReadiness === "READY" ? "READY" : analysis.captureReadiness === "ALMOST_READY" ? "ALMOST_READY" : analysis.refinementResult.geometry || analysis.fusionResult.geometry ? "DOCUMENT_CANDIDATE_FOUND" : "SEARCHING_FOR_DOCUMENT"; this.set({ state, analysis, guidance: analysis.guidance, error: undefined, workerMessages: [...this.current.workerMessages, `ANALYZE_FRAME:${analysis.engineMode}`] }); return analysis; } catch (error) { this.set({ state: "ERROR", error: error instanceof Error ? error.message : "analysis failed" }); throw error; } }
  requestCapture(mode: CaptureMode): boolean { if (mode === "AUTO" && this.current.analysis?.captureReadiness !== "CAPTURE_NOW") return false; this.set({ state: "CAPTURING", guidance: ["CAPTURING"] }); return true; }
  addCapturedPage(id: string, sourceUri: string, sourceSize: ImageSize, thumbnailUri?: string): string { let session = addDraftPage(this.current.session, id, sourceUri, sourceSize); const geometry = this.current.analysis?.refinementResult.geometry ?? this.current.analysis?.fusionResult.geometry; if (geometry) session = attachGeometry(session, id, { ...geometry, imageSize: sourceSize, corners: geometry.corners.map((point) => ({ x: point.x * sourceSize.width / geometry.imageSize.width, y: point.y * sourceSize.height / geometry.imageSize.height })) as unknown as PageGeometry["corners"] }); this.set({ state: "REVIEWING_PAGE", session, activePageId: id, guidance: [] }); return id; }
  applyManualCrop(pageId: string, geometry: PageGeometry): void { const session = attachGeometry(this.current.session, pageId, { ...geometry, source: "MANUAL" }); this.set({ state: "REVIEWING_PAGE", session, activePageId: pageId }); }
  resetCrop(pageId: string): void { const page = pageById(this.current.session, pageId); this.set({ session: updatePage(this.current.session, { ...page, manualGeometry: undefined }) }); }
  deletePage(pageId: string): void { const session = deletePage(this.current.session, pageId); this.set({ session, activePageId: session.pages[0]?.id, state: session.pages.length ? "REVIEWING_PAGE" : "SEARCHING_FOR_DOCUMENT" }); }
  reorderPages(from: number, to: number): void { this.set({ session: reorderPage(this.current.session, from, to) }); }
  rotatePage(pageId: string): void { this.set({ session: rotatePage(this.current.session, pageId) }); }
  selectPage(pageId: string): void { pageById(this.current.session, pageId); this.set({ state: "REVIEWING_PAGE", activePageId: pageId }); }
  async reconstructPage(pageId: string): Promise<ReconstructionResult> { const page = pageById(this.current.session, pageId); const geometry = effectiveGeometry(page); if (!geometry) throw new Error("a valid detected or manual geometry is required"); this.set({ state: "APPLYING_FILTER", session: updatePage(this.current.session, { ...page, state: "RECONSTRUCTING", processingStatus: "RUNNING" }) }); const result = await this.engine.reconstructPage({ pageId, sourceUri: page.sourceUri, sourceSize: page.sourceSize, geometry, outputLongEdge: 2048, aspectPolicy: "free_from_quad", orientationPolicy: "preserve_source", cropMarginPolicy: "safe_inner" }); const latest = pageById(this.current.session, pageId); this.set({ state: "REVIEWING_PAGE", session: updatePage(this.current.session, { ...latest, canonicalPage: { uri: result.outputUri, size: result.outputSize, diagnostics: result.diagnostics }, state: "READY", processingStatus: "COMPLETE", diagnostics: [...latest.diagnostics, ...result.diagnostics] }), workerMessages: [...this.current.workerMessages, "RECONSTRUCT_PAGE"] }); return result; }
  async applyFilter(pageId: string, preset: FilterPreset): Promise<FilterResult> { const page = pageById(this.current.session, pageId); this.set({ state: "APPLYING_FILTER" }); const result = await this.engine.applyFilter({ pageId, inputUri: page.canonicalPage?.uri ?? page.sourceUri, preset, conditionVector: this.current.analysis?.conditionVector ?? { conditions: {} } }); const latest = pageById(this.current.session, pageId); this.set({ state: "REVIEWING_PAGE", session: updatePage(this.current.session, { ...latest, filter: preset, processingStatus: "COMPLETE", diagnostics: [...latest.diagnostics, ...result.diagnostics] }), workerMessages: [...this.current.workerMessages, "APPLY_FILTER"] }); return result; }
}
