import type { ImageSize, Point2D } from "../../../shared/src/scan-session.js";
export type PreviewScaleMode = "FIT" | "FILL";
export interface CanvasSize { readonly width: number; readonly height: number; readonly devicePixelRatio: number; }
export class CanvasCoordinateMapper {
  private readonly rotated: ImageSize; private readonly scale: number; private readonly offsetX: number; private readonly offsetY: number;
  constructor(private readonly image: ImageSize, private readonly canvas: CanvasSize, private readonly rotation: 0 | 90 | 180 | 270 = 0, private readonly mode: PreviewScaleMode = "FIT", private readonly mirrored = false) { this.rotated = rotation === 90 || rotation === 270 ? { width: image.height, height: image.width } : image; this.scale = (mode === "FIT" ? Math.min : Math.max)(canvas.width / this.rotated.width, canvas.height / this.rotated.height) * canvas.devicePixelRatio; this.offsetX = (canvas.width * canvas.devicePixelRatio - this.rotated.width * this.scale) / 2; this.offsetY = (canvas.height * canvas.devicePixelRatio - this.rotated.height * this.scale) / 2; }
  imageToCanvas(point: Point2D): Point2D { let x = point.x; let y = point.y; if (this.rotation === 90) [x, y] = [this.image.height - point.y, point.x]; if (this.rotation === 180) [x, y] = [this.image.width - point.x, this.image.height - point.y]; if (this.rotation === 270) [x, y] = [point.y, this.image.width - point.x]; if (this.mirrored) x = this.rotated.width - x; return { x: this.offsetX + x * this.scale, y: this.offsetY + y * this.scale }; }
  canvasToImage(point: Point2D): Point2D { let x = (point.x - this.offsetX) / this.scale; let y = (point.y - this.offsetY) / this.scale; if (this.mirrored) x = this.rotated.width - x; let result: Point2D = { x, y }; if (this.rotation === 90) result = { x: y, y: this.image.height - x }; if (this.rotation === 180) result = { x: this.image.width - x, y: this.image.height - y }; if (this.rotation === 270) result = { x: this.image.width - y, y: x }; return { x: Math.max(0, Math.min(this.image.width, result.x)), y: Math.max(0, Math.min(this.image.height, result.y)) }; }
}
