import { effectiveGeometry, type FilterPreset, type PageGeometry, type Point2D } from "../../../shared/src/scan-session.js";
import { CanvasCoordinateMapper } from "../geometry/coordinate-mapping.js";
import { WebCameraController } from "../camera/web-camera.js";
import { frameFromImportedImage, importBrowserImage, type ImportedImage } from "../import/browser-image.js";
import { ObjectUrlRegistry } from "../import/object-url-registry.js";
import { exportDebugJson } from "../export/debug-export.js";
import { WebScanController } from "../scanner/controller.js";

const uiGuidance: Record<string, string> = { NO_DOCUMENT: "Find a document", MOVE_CLOSER: "Move closer", MOVE_FARTHER: "Move farther", HOLD_STEADY: "Hold steady", TOO_DARK: "More light needed", TOO_BRIGHT: "Reduce exposure", TOO_BLURRY: "Hold still", GLARE_DETECTED: "Reduce glare", DOCUMENT_CUT_OFF: "Keep all edges visible", LOW_CONFIDENCE: "Improve framing", LOW_DETECTOR_AGREEMENT: "Improve framing", READY: "Ready", CAPTURING: "Capturing" };

/** Dependency-free reference UI. It calls only WebScanController and browser APIs. */
export class ScannerShell {
  private readonly assets = new Map<string, ImportedImage>(); private readonly urls = new ObjectUrlRegistry(); private readonly camera = new WebCameraController();
  private readonly input = document.createElement("input"); private readonly video = document.createElement("video"); private readonly image = document.createElement("img"); private readonly canvas = document.createElement("canvas"); private readonly status = document.createElement("output"); private readonly diagnostics = document.createElement("pre"); private readonly pages = document.createElement("ol"); private activeCrop?: PageGeometry; private dragging?: number;
  constructor(private readonly root: HTMLElement, private readonly controller: WebScanController) { this.build(); }
  private build(): void {
    this.root.className = "wellfriend-scanner"; this.input.type = "file"; this.input.accept = "image/jpeg,image/png,image/webp"; this.input.multiple = true; this.video.autoplay = true; this.video.playsInline = true; this.canvas.tabIndex = 0;
    const importButton = this.button("Import images", () => this.input.click()); const cameraButton = this.button("Start camera", () => void this.startCamera()); const captureButton = this.button("Capture camera", () => void this.captureCamera()); const exportButton = this.button("Download debug JSON", () => this.downloadDebug());
    const filters = ["ORIGINAL", "AUTO", "CLEAN", "COLOR", "GRAYSCALE", "BLACK_AND_WHITE"] as const; const filterPanel = document.createElement("div"); filters.forEach((preset) => filterPanel.append(this.button(preset, () => void this.applyFilter(preset))));
    const advanced = document.createElement("p"); advanced.textContent = "Receipt, Book, Whiteboard, and Photo Document are declared advanced filters and remain deferred.";
    const cropPanel = document.createElement("div"); cropPanel.append(this.button("Apply crop", () => this.applyCrop()), this.button("Reset crop", () => this.resetCrop()), this.button("Reconstruct", () => void this.reconstruct()), this.button("Rotate", () => this.rotateActive()), this.button("Delete page", () => this.deleteActive()));
    const dropZone = document.createElement("section"); dropZone.className = "drop-zone"; dropZone.textContent = "Drop JPEG, PNG, or WebP images here"; dropZone.ondragover = (event) => event.preventDefault(); dropZone.ondrop = (event) => { event.preventDefault(); void this.importFiles(event.dataTransfer?.files ?? null, "upload"); };
    this.input.onchange = () => void this.importFiles(this.input.files, "upload"); this.canvas.onpointerdown = (event) => this.beginDrag(event); this.canvas.onpointermove = (event) => this.drag(event); this.canvas.onpointerup = () => { this.dragging = undefined; };
    const header = document.createElement("header"); header.append(importButton, cameraButton, captureButton, exportButton); const review = document.createElement("aside"); review.append(document.createElement("h2"), this.pages); review.querySelector("h2")!.textContent = "Pages";
    this.root.append(header, dropZone, this.input, this.video, this.image, this.canvas, this.status, cropPanel, filterPanel, advanced, review, document.createElement("h2"), this.diagnostics); this.root.querySelectorAll("h2")[1].textContent = "Diagnostics";
  }
  private button(text: string, handler: () => void): HTMLButtonElement { const button = document.createElement("button"); button.type = "button"; button.textContent = text; button.onclick = handler; return button; }
  private async importFiles(files: FileList | null, source: ImportedImage["source"]): Promise<void> { if (!files) return; for (const file of Array.from(files)) await this.importFile(file, source); }
  private async importFile(file: Blob, source: ImportedImage["source"]): Promise<void> { try { const id = crypto.randomUUID(); const imported = await importBrowserImage(file, id, source); this.assets.set(id, imported); this.urls.track(id, imported.objectUrl); const decoded = await frameFromImportedImage(imported); await this.controller.registerSourceImage(imported.objectUrl, { width: decoded.size.width, height: decoded.size.height, stride: decoded.rowStrideBytes, pixelFormat: decoded.pixelFormat, bytes: new Uint8Array(decoded.bytes) }); const frame = { frameId: id, timestampMillis: Date.now(), size: decoded.size, rotationDegrees: 0 as const, mimeType: imported.mimeType, bytes: decoded.bytes, source, mirrored: false }; await this.controller.analyzeFrame(frame); this.controller.addCapturedPage(id, imported.objectUrl, imported.size, imported.thumbnailUrl); this.controller.selectPage(id); this.image.src = imported.objectUrl; await this.image.decode(); this.activeCrop = effectiveGeometry(this.controller.state.session.pages.find((page) => page.id === id)!); this.render(); } catch (error) { this.status.textContent = error instanceof Error ? error.message : "image import failed"; } }
  private async startCamera(): Promise<void> { try { await this.camera.start(this.video); this.status.textContent = "Camera preview started"; } catch (error) { this.status.textContent = error instanceof Error ? error.message : "camera unavailable"; } }
  private async captureCamera(): Promise<void> { try { const blob = await this.camera.capture(this.video); await this.importFile(new File([blob], "camera.jpg", { type: "image/jpeg" }), "camera"); } catch (error) { this.status.textContent = error instanceof Error ? error.message : "camera capture failed"; } }
  private activePage() { const id = this.controller.state.activePageId; return id ? this.controller.state.session.pages.find((page) => page.id === id) : undefined; }
  private mapper(): CanvasCoordinateMapper | undefined { const page = this.activePage(); if (!page) return undefined; return new CanvasCoordinateMapper(page.sourceSize, { width: this.canvas.clientWidth || page.sourceSize.width, height: this.canvas.clientHeight || page.sourceSize.height, devicePixelRatio: devicePixelRatio || 1 }); }
  private render(): void { const state = this.controller.state; this.status.textContent = state.guidance.map((code) => uiGuidance[code] ?? code).join(" · ") || state.state; const page = this.activePage(); this.pages.replaceChildren(...state.session.pages.map((item, index) => { const li = document.createElement("li"); const select = this.button(`${index + 1}. ${item.id.slice(0, 8)}`, () => { this.controller.selectPage(item.id); this.image.src = this.assets.get(item.id)?.objectUrl ?? item.sourceUri; this.activeCrop = effectiveGeometry(item); this.render(); }); li.append(select); return li; })); this.diagnostics.textContent = JSON.stringify({ engineMode: this.controller.engineMode, state: state.state, sourceSize: page?.sourceSize, canvas: { width: this.canvas.clientWidth, height: this.canvas.clientHeight, devicePixelRatio }, guidance: state.guidance, quality: state.analysis?.qualityReport.metrics, confidence: state.analysis?.fusionResult.confidence, readiness: state.analysis?.captureReadiness, timings: state.analysis?.stageTimingsMillis, workerMessages: state.workerMessages, pageDiagnostics: page?.diagnostics }, null, 2); this.drawOverlay(); }
  private drawOverlay(): void { const page = this.activePage(); const mapper = this.mapper(); if (!page || !mapper) return; const width = this.canvas.clientWidth || page.sourceSize.width; const height = this.canvas.clientHeight || page.sourceSize.height; this.canvas.width = width * devicePixelRatio; this.canvas.height = height * devicePixelRatio; const context = this.canvas.getContext("2d"); if (!context) return; context.clearRect(0, 0, this.canvas.width, this.canvas.height); const geometry = this.activeCrop ?? effectiveGeometry(page); if (!geometry) return; const points = geometry.corners.map((point) => mapper.imageToCanvas(point)); context.strokeStyle = "#67e8f9"; context.lineWidth = 3 * devicePixelRatio; context.beginPath(); points.forEach((point, index) => index ? context.lineTo(point.x, point.y) : context.moveTo(point.x, point.y)); context.closePath(); context.stroke(); points.forEach((point) => { context.fillStyle = "#fef08a"; context.beginPath(); context.arc(point.x, point.y, 8 * devicePixelRatio, 0, Math.PI * 2); context.fill(); }); }
  private beginDrag(event: PointerEvent): void { const geometry = this.activeCrop; const mapper = this.mapper(); if (!geometry || !mapper) return; const pointer = { x: event.offsetX * devicePixelRatio, y: event.offsetY * devicePixelRatio }; const index = geometry.corners.map((point) => mapper.imageToCanvas(point)).findIndex((point) => Math.hypot(point.x - pointer.x, point.y - pointer.y) < 24 * devicePixelRatio); if (index >= 0) { this.dragging = index; this.canvas.setPointerCapture(event.pointerId); } }
  private drag(event: PointerEvent): void { if (this.dragging === undefined || !this.activeCrop) return; const mapper = this.mapper(); if (!mapper) return; const point = mapper.canvasToImage({ x: event.offsetX * devicePixelRatio, y: event.offsetY * devicePixelRatio }); const corners = [...this.activeCrop.corners] as Point2D[]; corners[this.dragging] = point; this.activeCrop = { ...this.activeCrop, corners: corners as unknown as PageGeometry["corners"], confidence: 1, source: "MANUAL" }; this.drawOverlay(); }
  private applyCrop(): void { const page = this.activePage(); if (!page || !this.activeCrop) return; try { this.controller.applyManualCrop(page.id, { ...this.activeCrop, source: "MANUAL" }); this.render(); } catch (error) { this.status.textContent = error instanceof Error ? error.message : "invalid crop"; } }
  private resetCrop(): void { const page = this.activePage(); if (!page) return; this.controller.resetCrop(page.id); this.activeCrop = effectiveGeometry(this.activePage()!); this.render(); }
  private async reconstruct(): Promise<void> { const page = this.activePage(); if (!page) return; await this.controller.reconstructPage(page.id); this.render(); }
  private async applyFilter(preset: FilterPreset): Promise<void> { const page = this.activePage(); if (!page) return; await this.controller.applyFilter(page.id, preset); this.render(); }
  private rotateActive(): void { const page = this.activePage(); if (!page) return; this.controller.rotatePage(page.id); this.render(); }
  private deleteActive(): void { const page = this.activePage(); if (!page) return; this.urls.release(page.id); this.assets.delete(page.id); this.controller.deletePage(page.id); this.image.removeAttribute("src"); this.activeCrop = undefined; this.render(); }
  private downloadDebug(): void { try { const result = exportDebugJson({ session: this.controller.state.session, format: "JSON_DEBUG" }); if (!result.blob) return; const url = URL.createObjectURL(result.blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `wellfriend-scan-${this.controller.state.session.id}.json`; anchor.click(); URL.revokeObjectURL(url); } catch (error) { this.status.textContent = error instanceof Error ? error.message : "export failed"; } }
  dispose(): void { this.camera.stop(); this.assets.clear(); this.urls.dispose(); }
}
